#!groovy

// Generated by IBM TransformationAdvisor
// Mon Feb 18 20:05:37 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'modresorts10war'
    mvnCommands = '--version'
    test='false'
}